[variables]
NODE_ENV = "production"
PATH = "$HOME/.bun/bin:$PATH"

[phases.setup]
nixPkgs = ["nodejs_20", "curl"]

[phases.install]
cmds = ["curl -fsSL https://bun.sh/install | bash", "bun install --production=false"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "node start-server.js"

